apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: minio-client-deployment
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: minio-client
    spec:
      containers:
        - name: minio-client
          image: docker.io/opsmx11/minio-client:demo
          imagePullPolicy: Always
          env:
            - name: minio1Endpoint
              valueFrom:
                secretKeyRef:
                  name: mcclient
                  key: minio1endpoint
            - name: minio1Accesskey
              valueFrom:
                secretKeyRef:
                  name: mcclient
                  key: minio1accesskey
            - name: minio1Secretaccess
              valueFrom:
                secretKeyRef:
                  name: mcclient
                  key: minio1secretaccess
            - name: minio2Endpoint
              valueFrom:
                secretKeyRef:
                  name: mcclient
                  key: minio2endpoint
            - name: minio2Accesskey
              valueFrom:
                secretKeyRef:
                  name: mcclient
                  key: minio2accesskey 
            - name: minio2Secretaccess
              valueFrom:
                secretKeyRef:
                  name: mcclient
                  key: minio2secretaccess
            - name: bucket1
              valueFrom:
                secretKeyRef:
                  name: mcclient
                  key: bucket1
            - name: bucket2
              valueFrom:
                secretKeyRef:
                  name: mcclient
                  key: bucket2
          command: [ "/bin/sh", "-c"]
          args: [ "sh /data/replication.sh"]
          volumeMounts:
            - mountPath: /backup
              name: mc-data 
      volumes: 
        - name: mc-data
          persistentVolumeClaim: 
            claimName: mc
